import os
import json

word_phoneme_table = {}

with open('cmudict.txt', 'r', encoding='latin-1') as fp:
    for line in fp.readlines():
        if line.startswith(';;;'):
            continue

        line = line.strip()
        # TODO: parse the stress number properly

        word_info = line.split()
        word = word_info[0]
        phonemes = word_info[1:]

        for i, pho in enumerate(phonemes):
            pho_strip = ''
            for c in pho:
                if c.isdigit():
                    continue

                pho_strip += c

            phonemes[i] = pho_strip
        word_phoneme_table[word] = ' '.join(phonemes)

with open('../src/engine/cmu.js', 'w') as fp:
    fp.write(f'// Autogenerated CMU Dictionary (by {os.path.basename(__file__)} ) - DO NOT EDIT\n')
    fp.write('export const wordPhonemes = {\n')

    for word, phonemes in word_phoneme_table.items():
        fp.write(f'\t{repr(word)}: "{phonemes}",\n')

    fp.write('};\n')
